services:
  web:
    build: .
    image: youtubick_app:latest
    container_name: youtubick_app
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file: .env
    environment:
      - BTC_ADDRESS=${BTC_ADDRESS}
      - ETH_ADDRESS=${ETH_ADDRESS}
      - SOL_ADDRESS=${SOL_ADDRESS}
      - HTTPS_METHOD=redirect
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
    volumes:
      - /var/www/static:/app/static:ro