services:
  web:
    build: .
    image: fastapi_app:latest
    container_name: fastapi_app
    user: "1000:1000"
    #    ports:
    #      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - redis
    env_file: .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - BTC_ADDRESS=${BTC_ADDRESS}
      - ETH_ADDRESS=${ETH_ADDRESS}
      - SOL_ADDRESS=${SOL_ADDRESS}
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${SMTP_USER}
      - HTTPS_METHOD=redirect
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
    volumes:
      - ./app/static:/app/static:ro
      - shared_data:/app/uploads
      - logs_data:/app/logs
    expose:
      - "8080"
    networks:
      - youtubick_network
        - nginx-proxy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/healthchecker" ]
      interval: 30s
      timeout: 5s
      retries: 3

  worker:
    image: fastapi_app:latest
    container_name: celery_worker
    depends_on:
      - redis
    user: "1000:1000"
    env_file: .env
    restart: unless-stopped

    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    command: celery -A config.config worker --loglevel=info
    volumes:
      - shared_data:/app/uploads
      - logs_data:/app/logs
    networks:
      - youtubick_network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - youtubick_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 3

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "127.0.0.1:8443:8443"
      - "127.0.0.1:80:80"
    restart: unless-stopped
    volumes:
      - ./vhost.d:/etc/nginx/vhost.d:ro
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - ./app/static:/app/static:ro
    networks:
      - youtubick_network
      - nginx-proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - /usr/share/nginx/html:/usr/share/nginx/html
    networks:
      - youtubick_network
      - nginx-proxy


networks:
  youtubick_network:
    name: youtubick_network
  nginx-proxy:
    external: true

volumes:
  certs:
  redis_data:
    name: youtubick_redis_data
  shared_data:
    name: youtubick_shared_data
    external: true
  logs_data:
    name: youtubick_logs_data
    external: true

